server:
  port: 8761

eureka:
  instance:
    hostname: localhost77
  client:
    registerWithEureka: false44
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/